spring:
  application:
    name: eureka-client-config
  cloud:
    config:
      #uri: http://localhost:8111
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
